### PR TITLE
Added update for chunked upload

### PR DESCRIPTION
**Pull request by stesteau**

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @moskiteau,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by kaltura-hooks** [comment]
Hi @moskiteau,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by kaltura-hooks** [comment]
Hi @moskiteau,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by stesteau** [comment]
I just signed the CLA

**Comment by jessp01** [comment]
Thanks @moskiteau  - merged:)

**Pull request merged**
